In [10]:
import torch
import numpy as np

# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
y = x ** 2
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


In [12]:
z = y + 1
print(z)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [13]:
z.backward(torch.ones(2, 2))
print(z)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [14]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
