In [8]:
from __future__ import print_function
import torch
import numpy as np

x = torch.empty(5, 3)
print(x)

y = torch.rand(5, 3)
print(y)

z = np.zeros(5)
print(z)

a = [1, 2, 3]
b = [4, 5, 6]

c = np.convolve(a, b)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.2095, 0.2687, 0.3848],
        [0.1514, 0.3587, 0.7407],
        [0.2993, 0.1628, 0.9468],
        [0.8656, 0.4709, 0.7448],
        [0.9847, 0.4630, 0.2560]])
[0. 0. 0. 0. 0.]
[ 4 13 28 27 18]
