In [1]:
from __future__ import print_function
import torch
import numpy as np

x = torch.empty(5, 3)
print(x)

y = torch.rand(5, 3)
print(y)

z = np.zeros(5)
print(z)

a = [1, 2, 3]
b = [4, 5, 6]

c = np.convolve(a, b)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1100, 0.8066, 0.3860],
        [0.8420, 0.9436, 0.0072],
        [0.1505, 0.2003, 0.7687],
        [0.1411, 0.9896, 0.9635],
        [0.5039, 0.3967, 0.7788]])
[0. 0. 0. 0. 0.]
[ 4 13 28 27 18]
